# Generated by Django 3.2.10 on 2021-12-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_order_products_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceeds', models.PositiveIntegerField(default=0, verbose_name='выручка')),
                ('earnings', models.IntegerField(default=0, verbose_name='прибыль')),
                ('number_of_sold', models.PositiveIntegerField(default=0, verbose_name='количество проданных')),
                ('number_of_canceled', models.PositiveIntegerField(default=0, verbose_name='количество возвратов')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'отчеты',
            },
        ),
    ]
