version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: backend
    restart: always
    tty: true
    command: sh -c "cd src && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .envfile
    depends_on:
      - pg_db
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  celery:
    image: backend
    working_dir: /app
    command: sh -c "celery -A backend.celery worker -l info"
    volumes:
      - ./src:/app
    env_file:
      - .envfile
    depends_on:
      - backend
    restart: always
    container_name: celery
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  pg_db:
    image: postgres:13-alpine
    container_name: pg_db
    restart: unless-stopped
    env_file:
      - .envfile
    ports:
      - "5432:5432"
    volumes:
      - shop_pg_db:/var/lib/postgresql/data
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '1'

  redis:
    image: redis:alpine
    working_dir: /data
    expose:
      - '6379'
    volumes:
      - /data:/data
    container_name: redis
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '1'

volumes:
  shop_pg_db:
  redis:
