version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    container_name: backend
    restart: always
    tty: true
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .envfile
    depends_on:
      - pg_db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  pg_db:
    image: postgres:13-alpine
    container_name: pg_db
    restart: unless-stopped
    env_file:
      - .envfile
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '1'

volumes:
  db-data:
