# Generated by Django 4.0 on 2021-12-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='название')),
                ('cost_price', models.PositiveIntegerField(verbose_name='себестоимость')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('quantity', models.IntegerField(verbose_name='количество')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
