# Generated by Django 4.0 on 2021-12-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='дата создания')),
                ('status', models.CharField(choices=[('canceled', 'отменен'), ('on_processing', 'на обработке')], max_length=13, verbose_name='статус')),
                ('total_cost_price', models.PositiveIntegerField(verbose_name='итоговая себестоимость')),
                ('total_price', models.PositiveIntegerField(verbose_name='итоговая цена')),
                ('products_quantity', models.PositiveIntegerField(verbose_name='количество продуктов')),
                ('products', models.ManyToManyField(to='products.Product', verbose_name='продукты')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
