# Generated by Django 4.0 on 2021-12-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_orderedproduct_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='количество продуктов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost_price',
            field=models.PositiveIntegerField(default=0, verbose_name='итоговая себестоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='итоговая цена'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='количество продуктов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.PositiveIntegerField(default=0, verbose_name='себестоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
    ]
