# Generated by Django 3.2.10 on 2021-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_order_products_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'отменен'), ('on_processing', 'на обработке'), ('done', 'завершен')], max_length=13, verbose_name='статус'),
        ),
    ]
